from django.conf.urls import patterns, url
from WONKA import views

urlpatterns = patterns('',
    url(r'^(?P<target_id>\d+)/Summarise/$', views.Summarise, name='Summarise'),
    url(r'^(?P<target_id>\d+)/SummariseORIG/$', views.SummariseORIG, name='SummariseORIG'),
    url(r'^(?P<target_name>\w+)/SummariseCheck/$', views.SummariseCheck, name='SummariseCheck'),
    url(r'^(?P<obs_id>\d+)/SummariseBack/$', views.SummariseBack, name='SummariseBack'),
    url(r'^ScoreMol/$', views.ScoreMol, name='ScoreMol'),
    url(r'^show_point/$', views.show_point, name='show_point'),
    url(r'^register_observation/$', views.register_observation, name='register_observation'),
    url(r'^register_user/$', views.register_user, name='register_user'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^add_comment/$', views.add_comment, name='add_comment'),
    url(r'^(?P<prot_id>\d+)/get_grob/$', views.get_grob, name='get_grob'),
    url(r'^get_interactions/$', views.get_interactions, name='get_interactions'),
    url(r'^request_observation/$', views.request_observation, name='request_observation'),
    url(r'^(?P<target_id>\d+)/ShowObservations/$', views.ShowObservations, name='ShowObservations'),
    url(r'^(?P<target_id>\d+)/fp_view/$', views.fp_view, name='fp_view'),
    url(r'^get_targ_fps/$', views.get_targ_fps, name='get_targ_fps'),
    url(r'^mol_view/$', views.mol_view, name='mol_view'),
    url(r'^(?P<target_id>\d+)/SplitSet/$', views.SplitSet, name='SplitSet'),
    url(r'^(?P<target_id>\d+)/view_clusts/$', views.view_clusts, name='view_clusts'),
    url(r'^(?P<target_id>\d+)/get_cluster/$', views.get_cluster, name='get_cluster'),
    url(r'^get_pot_ph4s/$', views.get_pot_ph4s, name='get_pot_ph4s'),
    url(r'^seen_mol/$', views.seen_mol, name='seen_mol'),
    url(r'^(?P<target_id>\d+)/get_frags/$', views.get_frags, name='get_frags'),
    url(r'^(?P<uuid>[^/]+)/ShowObs/$', views.ShowObs, name='ShowObs'),
    url(r'^(?P<user_pk>\d+)/get_user_info/$', views.get_user_info, name='get_user_info'),
    url(r'^(?P<cluster_pk>\d+)/get_oommppaa_infos/$', views.get_oommppaa_infos, name='get_oommppaa_infos'),
    url(r'^(?P<target_id>\d+)/(?P<user_id>\d+)/unsubscribe_targ/$', views.unsubscribe_targ, name='unsubscribe_targ'),
    url(r'^(?P<target_id>\d+)/(?P<user_id>\d+)/subscribe_targ/$', views.subscribe_targ, name='subscribe_targ'),
    url(r'^subscribe_to_disqus/$', views.subscribe_to_disqus, name='subscribe_to_disqus'),
    url(r'^FindObservations/$', views.FindObservations, name='FindObservations'),
    url(r'^(?P<mol_id>\d+)/get_map/$', views.get_map, name='get_map'),
    url(r'^$', views.index, name='index'),
)